### ISSUE TITLE
java.lang.Exception in ExampleActivity

### ISSUE THREAD

**Issue by xander-jones** [xander-jones/bugsnag-testing#2]
## Error in Xander Android Test

**java.lang.Exception** in **ExampleActivity**
Here's some info!

[View on Bugsnag](https://app.bugsnag.com/bugsnag-test-projects/xander-android-test/errors/5eec868ec4b6110017f50212?event_id=5eec868e005b8ea95f4e0000&i=gh&m=ci)

## Stacktrace

    ExampleActivity.kt:63 - com.bugsnag.android.example.ExampleActivity.crashHandled

[View full stacktrace](https://app.bugsnag.com/bugsnag-test-projects/xander-android-test/errors/5eec868ec4b6110017f50212?event_id=5eec868e005b8ea95f4e0000&i=gh&m=ci)

*Created automatically via Bugsnag*

**Comment by integrations-test** [comment]
This issue has been linked to an error in Bugsnag
[**Bad beans** in **file.java:300**](https://website:3000/test-org/test-project/errors/5f0eb3ac1e84c400202e024a?event_id=5f0eb3bf0000021aaacf0000&i=gh&m=li)
